config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tests#index' 
  resources :tests do
    resources :questions, except: [:index, :show]
    resources :answers do
      get 'new_answer', on: :collection
      post 'save_answers', on: :collection
    end
    resources :results
    resources :groups
  end
end

app/models/question.rb
# Question
class Question < ActiveRecord::Base
  belongs_to :test
  belongs_to :group
  has_many :answers
  validates :num, uniqueness: { scope: :test_id }
end

app/controllers/questions_controller.rb
# QuestionsController
class QuestionsController < ApplicationController
  before_action :load_test
  before_action :load_groups
  before_action :load_question, only: [:edit, :update, :destroy]

  def new
    @question = Question.new
    @num = @test.questions.any? ? @test.questions.maximum(:num) + 1 : 1
  end

  def create
    @question = Question.new(set_params.merge(test_id: @test.id)) 

    if @question.save
      redirect_to new_test_question_path(@test)
    else
      render 'new'
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update   
    if @question.update(set_params)
      redirect_to test_path(@test)
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    redirect_to(:back)
  end

  private

  def load_test
    @test = Test.find(params[:test_id]) 
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def load_groups
    @groups = @test.groups
  end

  def set_params
    params.require(:question).permit(:num, :group_id, :back, :body)
  end
end

app/views/questions/edit.html.haml
%h4 Редактирование вопроса № "#{@question.num}"      
= simple_form_for [@test, @question], method: :put do |f|
  %table{:class => 'table table-striped table-bordered'}
    %tr
      %td
        = f.input :back, label: 'Обратный'    
      %td
        = f.input :group_id, label: 'Группа', collection: @groups, label_method: :group_name, value_metod: :id, selected: 1  
    %tr 
      %td{:colspan => "2"}
        = f.input :body, label: 'Вопрос'    

  %p{:class => 'text-center'} 
    = link_to 'Назад', test_path(@test), class: "btn btn-default"
    = "   " 
    = f.button :submit, 'Сохранить', class: "btn btn-primary"
%br
%h4 Введенные вопросы
%table{:class => 'table table-striped table-bordered'}
  %tr
    %th{:class => 'text-center'} 
      Номер вопроса
    %th{:class => 'text-center'} 
      Группы
    %th{:class => 'text-center'}   
      Обратный
  - @test.questions.order(num: :desc).each do |q| 
    %tr
      %td{:class => 'text-center'}  
        = q.num
      %td 
        = q.group.group_name
      %td{:class => 'text-center'}  
        = q.back

app/views/questions/new.html.haml
%h3 Новый вопрос в тесте
= simple_form_for [@test, @question] do |f|
  %table{:class => 'table table-striped table-bordered'}
    %tr
      %td 
        = f.input :num, label: 'Порядковый номер', input_html: {value: "#{@num}"}
      %td
        = f.input :group_id, label: 'Группа', collection: @groups, label_method: :group_name, value_metod: :id, selected: 1
      %td
        = f.input :back, label: 'Обратный'    
    %tr
      %td{:colspan => "3"}
        = f.input :body, label: 'Вопрос'
  %p{:class => 'text-center'} 
    = link_to 'Назад', test_path(@test), class: "btn btn-default"    
    = "   " 
    = f.button :submit, 'Сохранить', class: "btn btn-primary"
  %br      
  %table{:class => 'table table-striped table-bordered'}
    %tr
      %th{:class => 'text-center'} Номер
      %th{:class => 'text-center'} Вопрос
      %th{:class => 'text-center'} Группа
      %th{:class => 'text-center'} Действия
    - @test.questions.order(num: :desc).each do |q| 
      %tr
        %td 
          = q.num
        %td 
          = q.body
        %td 
          = q.group.group_name
        %td{:class => 'text-center'}
          = link_to 'Редактировать', edit_test_question_path(@test, q), class: "btn btn-warning btn-xs btn-block"
          %p
          = link_to 'Удалить', test_question_path(@test, q), class: "btn btn-danger btn-xs btn-block", method: :delete, data: { confirm: 'точняк?' }