config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tests#index' 
  resources :tests do
    resources :questions, except: [:index, :show]
    resources :answers do
      get 'new_answer', on: :collection
      post 'save_answers', on: :collection
    end
    resources :results
    resources :groups
  end
end

app/models/group.rb
# Group
class Group < ActiveRecord::Base
  belongs_to :test
  has_many :questions
  validates :num, uniqueness: { scope: :test_id }
end

app/controllers/groups_controller.rb
# GroupsController
class GroupsController < ApplicationController
  before_action :load_test
  before_action :load_group, only: [:edit, :update, :destroy, :show]

  def new
    @group = Group.new
    @num = @test.groups.any? ? @test.groups.maximum(:num).to_i + 1 : 1
  end

  def create
    @group = Group.new(set_params.merge(test_id: @test.id))

    if @group.save
      redirect_to new_test_group_path(@test)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @group.update(set_params)
      redirect_to new_test_group_path(@test)
    else
      render 'edit'
    end
  end

  def destroy
    @group.destroy
    redirect_to(:back)
  end

  private

  def load_group
    @group = Group.find(params[:id])
  end

  def load_test
    @test = Test.find(params[:test_id])
  end

  def set_params
    params.require(:group).permit(:group_name, :rule, :num)
  end
end

app/views/groups/edit.html.haml
%h4 Редактирование вопроса № "#{@group.num}"      
= simple_form_for [@test, @group], method: :put do |f|
  %table{:class => 'table table-striped table-bordered'}
    %tr
      %td{:class => 'text-center'} 
        = f.input :num, label: '№ вопроса'
      %td{:class => 'text-center'} 
        = f.input :group_name, label: 'Имя группы'
      %td{:class => 'text-center'} 
        = f.input :rule, label: 'Правило'   
  %p{:class => 'text-center'} 
    = link_to 'Назад', test_path(@test), class: "btn btn-default"
    = "   " 
    = f.button :submit, 'Сохранить', class: "btn btn-primary"
%br
%h4 Введенные вопросы
%table{:class => 'table table-striped table-bordered'}
  %tr
    %th{:class => 'text-center'} № группы
    %th{:class => 'text-center'} Имя группы
    %th{:class => 'text-center'} Правило 
  - @test.groups.order(num: :desc).each do |q| 
    %tr
      %td 
        = q.num
      %td 
        = q.group_name
      %td 
        = q.rule

app/views/groups/new.html.haml
%h3 Группы для теста  "#{@test.name}"    
= simple_form_for [@test, @group] do |f|
  %table{:class => 'table table-striped table-bordered'}
    %tr
      %td{:class => 'text-center'} 
        = f.input :num, label: '№ группы', input_html: {value: "#{@num}"}    
      %td{:class => 'text-center'} 
        = f.input :group_name, label: 'Имя группы'
      %td{:class => 'text-center'} 
        = f.input :rule, label: 'Правило'
  %p{:class => 'text-center'}    
    = link_to 'Назад', test_path(@test), class: "btn btn-default"
    = "    " 
    = f.button :submit, 'Сохранить', class: "btn btn-primary"
  %br      
  %table{:class => 'table table-striped table-bordered'}
    %tr
      %th{:class => 'text-center'} № группы    
      %th{:class => 'text-center'} Имя группы
      %th{:class => 'text-center'} Правило
      %th{:class => 'text-center'} Действия
    - @test.groups.order(num: :desc).each do |q| 
      %tr
        %td{:class => 'text-center'} 
          = q.num      
        %td 
          = q.group_name
        %td{:class => 'text-center'} 
          = q.rule
        %td{:class => 'text-center'}
          = link_to 'Редактировать', edit_test_group_path(@test, q), class: "btn btn-warning btn-xs btn-block"
          %p
          = link_to 'Удалить', test_group_path(@test, q), class: "btn btn-danger btn-xs btn-block", method: :delete, data: { confirm: 'точняк?' }