config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tests#index' 
  resources :tests do
    resources :questions, except: [:index, :show]
    resources :answers do
      get 'new_answer', on: :collection
      post 'save_answers', on: :collection
    end
    resources :results
    resources :groups
  end
end

app/models/answer.rb
# Answer
class Answer < ActiveRecord::Base
  belongs_to :test
  belongs_to :question
  # validates :question_id, uniqueness: { scope: [:test_id, :user_id]}
end

app/controllers/answers_controller.rb
# AnswersController
class AnswersController < ApplicationController
  before_action :authenticate_user!, :load_test, :load_questions

  def new_answer
    answer = Answer.where(user_id: @user.id, test_id: @test.id).last
    @try_of = answer.try(:try_of).to_i + 1
  end

  def save_answers
    @questions.each do |q|
      Answer.create(answer_hash(q)) if params[q.id.to_s].present?
    end
    redirect_to test_path(@test)
  end

  private

  def load_test
    @test = Test.find(params[:test_id])
  end

  def load_questions
    @questions = @test.questions.order("RANDOM()")
  end

  def answer_hash(q)
    { name: params[q.id.to_s], question_id: q.id, test_id: @test.id, user_id: @user.id, try_of: params[:try_of] }
  end
end

app/views/answers/get_answ.html.haml
%h4 Тест: "#{@test.name}", попытка № "#{@try_of}"
= form_tag post_answ_test_answers_path(@test), { class: 'form-class', id: 'form-id', role: 'form', method: 'post' } do
  .form-group
    = hidden_field_tag "try_of", @try_of
    %table{:class => 'table table-bordered'}
      - @questions.each do |q|
        %tr
          %td
            %p
              = q.body
            %p
            %table{:class => 'table-condensed table-bordered text-center'}
              %tr
                - (1..@test.num_of_answ).each do |i|
                  %td
                    = label_tag(q.id, "#{i}")
                    - if i == @test.num_of_answ && @test.sp_answer?
                      %td
                        = label_tag(q.id, "Нет ответа")                                                    
              %tr
                - (1..@test.num_of_answ).each do |i|
                  %td
                    = radio_button_tag(q.id, "#{i}")
                    - if i == @test.num_of_answ && @test.sp_answer?
                      %td                    
                        = radio_button_tag(q.id, " ")
      %tr
        %td
          = link_to 'Назад', tests_path, class: "btn btn-default"
          = submit_tag("Отправить", class: "btn btn-default")

app/views/answers/new_answer.html.haml
%h4 Тест: "#{@test.name}", попытка № "#{@try_of}"
= form_tag save_answers_test_answers_path(@test), { class: 'form-class', id: 'form-id', role: 'form', method: 'post' } do
  .form-group
    = hidden_field_tag "try_of", @try_of
    %table{:class => 'table table-bordered'}
      - @questions.each do |q|
        %tr
          %td
            %p
              = q.body
            %p
            %table{:class => 'table-condensed table-bordered text-center'}
              %tr
                - (1..@test.num_of_answ).each do |i|
                  %td
                    = label_tag(q.id, "#{i}")
                    - if i == @test.num_of_answ && @test.sp_answer?
                      %td
                        = label_tag(q.id, "Нет ответа")                                                    
              %tr
                - (1..@test.num_of_answ).each do |i|
                  %td
                    = radio_button_tag(q.id, "#{i}")
                    - if i == @test.num_of_answ && @test.sp_answer?
                      %td                 
                        = radio_button_tag(q.id, " ")
      %tr
        %td
          %p{:class => 'text-center'}
            = link_to 'Назад', tests_path, class: "btn btn-default"
            = submit_tag("Отправить", class: "btn btn-default")